// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
  user_id,
  token_hash,
  expires_at
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, token_hash, expires_at, revoked, created_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  password_hash,
  full_name,
  persona,
  timezone,
  work_start,
  work_end
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, email, password_hash, full_name, persona, timezone, work_start, work_end, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	Persona      string      `json:"persona"`
	Timezone     string      `json:"timezone"`
	WorkStart    pgtype.Time `json:"work_start"`
	WorkEnd      pgtype.Time `json:"work_end"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Persona,
		arg.Timezone,
		arg.WorkStart,
		arg.WorkEnd,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Persona,
		&i.Timezone,
		&i.WorkStart,
		&i.WorkEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked, created_at FROM refresh_tokens
WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, persona, timezone, work_start, work_end, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Persona,
		&i.Timezone,
		&i.WorkStart,
		&i.WorkEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, persona, timezone, work_start, work_end, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Persona,
		&i.Timezone,
		&i.WorkStart,
		&i.WorkEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBriefingCandidates = `-- name: ListBriefingCandidates :many
SELECT id, email, full_name, persona, timezone, work_start, work_end
FROM users
`

type ListBriefingCandidatesRow struct {
	ID        pgtype.UUID `json:"id"`
	Email     string      `json:"email"`
	FullName  string      `json:"full_name"`
	Persona   string      `json:"persona"`
	Timezone  string      `json:"timezone"`
	WorkStart pgtype.Time `json:"work_start"`
	WorkEnd   pgtype.Time `json:"work_end"`
}

func (q *Queries) ListBriefingCandidates(ctx context.Context) ([]ListBriefingCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listBriefingCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBriefingCandidatesRow
	for rows.Next() {
		var i ListBriefingCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Persona,
			&i.Timezone,
			&i.WorkStart,
			&i.WorkEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked = true
WHERE user_id = $1
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked = true
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
  full_name = $2,
  persona = $3,
  timezone = $4,
  work_start = $5,
  work_end = $6,
  updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, full_name, persona, timezone, work_start, work_end, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID        pgtype.UUID `json:"id"`
	FullName  string      `json:"full_name"`
	Persona   string      `json:"persona"`
	Timezone  string      `json:"timezone"`
	WorkStart pgtype.Time `json:"work_start"`
	WorkEnd   pgtype.Time `json:"work_end"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.Persona,
		arg.Timezone,
		arg.WorkStart,
		arg.WorkEnd,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Persona,
		&i.Timezone,
		&i.WorkStart,
		&i.WorkEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
