// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Colour    string             `json:"colour"`
	Archived  bool               `json:"archived"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Subtask struct {
	ID       pgtype.UUID `json:"id"`
	TaskID   pgtype.UUID `json:"task_id"`
	Title    string      `json:"title"`
	Done     bool        `json:"done"`
	Position int32       `json:"position"`
}

type Tag struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

type Task struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Priority        int16              `json:"priority"`
	Status          string             `json:"status"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
	EstimateMinutes pgtype.Int4        `json:"estimate_minutes"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type TaskTag struct {
	TaskID pgtype.UUID `json:"task_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

type TimeBlock struct {
	ID       pgtype.UUID        `json:"id"`
	UserID   pgtype.UUID        `json:"user_id"`
	TaskID   pgtype.UUID        `json:"task_id"`
	Title    string             `json:"title"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}
