// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planner.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachTagToTask = `-- name: AttachTagToTask :exec
INSERT INTO task_tags (task_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AttachTagToTaskParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AttachTagToTask(ctx context.Context, arg AttachTagToTaskParams) error {
	_, err := q.db.Exec(ctx, attachTagToTask, arg.TaskID, arg.TagID)
	return err
}

const checkTimeBlockOverlap = `-- name: CheckTimeBlockOverlap :one
SELECT count(*) FROM time_blocks
WHERE user_id = $1
  AND id != $2
  AND starts_at < $3
  AND ends_at > $4
`

type CheckTimeBlockOverlapParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	ID               pgtype.UUID        `json:"id"`
	ProposedEndsAt   pgtype.Timestamptz `json:"proposed_ends_at"`
	ProposedStartsAt pgtype.Timestamptz `json:"proposed_starts_at"`
}

func (q *Queries) CheckTimeBlockOverlap(ctx context.Context, arg CheckTimeBlockOverlapParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkTimeBlockOverlap,
		arg.UserID,
		arg.ID,
		arg.ProposedEndsAt,
		arg.ProposedStartsAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
  user_id,
  name,
  colour
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, name, colour, archived, created_at, updated_at
`

type CreateProjectParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Colour string      `json:"colour"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.UserID, arg.Name, arg.Colour)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Colour,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubtask = `-- name: CreateSubtask :one
INSERT INTO subtasks (
  task_id,
  title,
  position
) VALUES (
  $1, $2, $3
)
RETURNING id, task_id, title, done, position
`

type CreateSubtaskParams struct {
	TaskID   pgtype.UUID `json:"task_id"`
	Title    string      `json:"title"`
	Position int32       `json:"position"`
}

func (q *Queries) CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (Subtask, error) {
	row := q.db.QueryRow(ctx, createSubtask, arg.TaskID, arg.Title, arg.Position)
	var i Subtask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Done,
		&i.Position,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (
  user_id,
  name
) VALUES (
  $1, $2
)
ON CONFLICT (user_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, user_id, name
`

type CreateTagParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  user_id,
  project_id,
  title,
  description,
  priority,
  status,
  due_at,
  estimate_minutes,
  completed_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, project_id, title, description, priority, status, due_at, estimate_minutes, completed_at, created_at, updated_at
`

type CreateTaskParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Priority        int16              `json:"priority"`
	Status          string             `json:"status"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
	EstimateMinutes pgtype.Int4        `json:"estimate_minutes"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.DueAt,
		arg.EstimateMinutes,
		arg.CompletedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.DueAt,
		&i.EstimateMinutes,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTimeBlock = `-- name: CreateTimeBlock :one
INSERT INTO time_blocks (
  user_id,
  task_id,
  title,
  starts_at,
  ends_at
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, user_id, task_id, title, starts_at, ends_at
`

type CreateTimeBlockParams struct {
	UserID   pgtype.UUID        `json:"user_id"`
	TaskID   pgtype.UUID        `json:"task_id"`
	Title    string             `json:"title"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateTimeBlock(ctx context.Context, arg CreateTimeBlockParams) (TimeBlock, error) {
	row := q.db.QueryRow(ctx, createTimeBlock,
		arg.UserID,
		arg.TaskID,
		arg.Title,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i TimeBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1 AND user_id = $2
`

type DeleteProjectParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.UserID)
	return err
}

const deleteSubtask = `-- name: DeleteSubtask :exec
DELETE FROM subtasks s
USING tasks t
WHERE s.task_id = t.id AND s.id = $1 AND t.user_id = $2
`

type DeleteSubtaskParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteSubtask(ctx context.Context, arg DeleteSubtaskParams) error {
	_, err := q.db.Exec(ctx, deleteSubtask, arg.ID, arg.UserID)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 AND user_id = $2
`

type DeleteTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	return err
}

const deleteTaskTagsByTaskID = `-- name: DeleteTaskTagsByTaskID :exec
DELETE FROM task_tags
WHERE task_id = $1
`

func (q *Queries) DeleteTaskTagsByTaskID(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskTagsByTaskID, taskID)
	return err
}

const deleteTimeBlock = `-- name: DeleteTimeBlock :exec
DELETE FROM time_blocks
WHERE id = $1 AND user_id = $2
`

type DeleteTimeBlockParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTimeBlock(ctx context.Context, arg DeleteTimeBlockParams) error {
	_, err := q.db.Exec(ctx, deleteTimeBlock, arg.ID, arg.UserID)
	return err
}

const detachTagFromTask = `-- name: DetachTagFromTask :exec
DELETE FROM task_tags
WHERE task_id = $1 AND tag_id = $2
`

type DetachTagFromTaskParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

func (q *Queries) DetachTagFromTask(ctx context.Context, arg DetachTagFromTaskParams) error {
	_, err := q.db.Exec(ctx, detachTagFromTask, arg.TaskID, arg.TagID)
	return err
}

const getOverdueTasks = `-- name: GetOverdueTasks :many
SELECT id, user_id, project_id, title, description, priority, status, due_at, estimate_minutes, completed_at, created_at, updated_at FROM tasks
WHERE user_id = $1 AND status != 'done' AND due_at < $2
ORDER BY due_at ASC
`

type GetOverdueTasksParams struct {
	UserID pgtype.UUID        `json:"user_id"`
	DueAt  pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) GetOverdueTasks(ctx context.Context, arg GetOverdueTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getOverdueTasks, arg.UserID, arg.DueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DueAt,
			&i.EstimateMinutes,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, user_id, name, colour, archived, created_at, updated_at FROM projects
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetProjectByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Colour,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, user_id, project_id, title, description, priority, status, due_at, estimate_minutes, completed_at, created_at, updated_at FROM tasks
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetTaskByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.DueAt,
		&i.EstimateMinutes,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasksForRange = `-- name: GetTasksForRange :many
SELECT id, title, due_at, estimate_minutes, status, priority FROM tasks
WHERE user_id = $1 AND due_at >= $2 AND due_at <= $3
ORDER BY due_at ASC
`

type GetTasksForRangeParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	DueAt   pgtype.Timestamptz `json:"due_at"`
	DueAt_2 pgtype.Timestamptz `json:"due_at_2"`
}

type GetTasksForRangeRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
	EstimateMinutes pgtype.Int4        `json:"estimate_minutes"`
	Status          string             `json:"status"`
	Priority        int16              `json:"priority"`
}

func (q *Queries) GetTasksForRange(ctx context.Context, arg GetTasksForRangeParams) ([]GetTasksForRangeRow, error) {
	rows, err := q.db.Query(ctx, getTasksForRange, arg.UserID, arg.DueAt, arg.DueAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTasksForRangeRow
	for rows.Next() {
		var i GetTasksForRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DueAt,
			&i.EstimateMinutes,
			&i.Status,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeBlockByID = `-- name: GetTimeBlockByID :one
SELECT id, user_id, task_id, title, starts_at, ends_at FROM time_blocks
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetTimeBlockByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTimeBlockByID(ctx context.Context, arg GetTimeBlockByIDParams) (TimeBlock, error) {
	row := q.db.QueryRow(ctx, getTimeBlockByID, arg.ID, arg.UserID)
	var i TimeBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const getTodayTasks = `-- name: GetTodayTasks :many
SELECT id, user_id, project_id, title, description, priority, status, due_at, estimate_minutes, completed_at, created_at, updated_at FROM tasks
WHERE user_id = $1 AND due_at >= $2 AND due_at <= $3
ORDER BY priority ASC, due_at ASC
`

type GetTodayTasksParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	DueAt   pgtype.Timestamptz `json:"due_at"`
	DueAt_2 pgtype.Timestamptz `json:"due_at_2"`
}

func (q *Queries) GetTodayTasks(ctx context.Context, arg GetTodayTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTodayTasks, arg.UserID, arg.DueAt, arg.DueAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DueAt,
			&i.EstimateMinutes,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingTasks = `-- name: GetUpcomingTasks :many
SELECT id, user_id, project_id, title, description, priority, status, due_at, estimate_minutes, completed_at, created_at, updated_at FROM tasks
WHERE user_id = $1 AND due_at > $2 AND due_at <= $3
ORDER BY due_at ASC
`

type GetUpcomingTasksParams struct {
	UserID  pgtype.UUID        `json:"user_id"`
	DueAt   pgtype.Timestamptz `json:"due_at"`
	DueAt_2 pgtype.Timestamptz `json:"due_at_2"`
}

func (q *Queries) GetUpcomingTasks(ctx context.Context, arg GetUpcomingTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getUpcomingTasks, arg.UserID, arg.DueAt, arg.DueAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.DueAt,
			&i.EstimateMinutes,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, user_id, name, colour, archived, created_at, updated_at FROM projects
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) ListProjects(ctx context.Context, userID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Colour,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtasksByTaskID = `-- name: ListSubtasksByTaskID :many
SELECT s.id, s.task_id, s.title, s.done, s.position FROM subtasks s
JOIN tasks t ON s.task_id = t.id
WHERE t.id = $1 AND t.user_id = $2
ORDER BY s.position ASC, s.id ASC
`

type ListSubtasksByTaskIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListSubtasksByTaskID(ctx context.Context, arg ListSubtasksByTaskIDParams) ([]Subtask, error) {
	rows, err := q.db.Query(ctx, listSubtasksByTaskID, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subtask
	for rows.Next() {
		var i Subtask
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.Done,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, user_id, name FROM tags
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context, userID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByTaskID = `-- name: ListTagsByTaskID :many
SELECT tg.id, tg.user_id, tg.name FROM tags tg
JOIN task_tags tt ON tg.id = tt.tag_id
WHERE tt.task_id = $1
ORDER BY tg.name ASC
`

func (q *Queries) ListTagsByTaskID(ctx context.Context, taskID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeBlocks = `-- name: ListTimeBlocks :many
SELECT id, user_id, task_id, title, starts_at, ends_at FROM time_blocks
WHERE user_id = $1
  AND starts_at >= $2
  AND ends_at <= $3
ORDER BY starts_at ASC
`

type ListTimeBlocksParams struct {
	UserID   pgtype.UUID        `json:"user_id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) ListTimeBlocks(ctx context.Context, arg ListTimeBlocksParams) ([]TimeBlock, error) {
	rows, err := q.db.Query(ctx, listTimeBlocks, arg.UserID, arg.StartsAt, arg.EndsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeBlock
	for rows.Next() {
		var i TimeBlock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Title,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
  name = $3,
  colour = $4,
  archived = $5,
  updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, colour, archived, created_at, updated_at
`

type UpdateProjectParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	Name     string      `json:"name"`
	Colour   string      `json:"colour"`
	Archived bool        `json:"archived"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Colour,
		arg.Archived,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Colour,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubtask = `-- name: UpdateSubtask :one
UPDATE subtasks s
SET
  title = $3,
  done = $4,
  position = $5
FROM tasks t
WHERE s.task_id = t.id AND s.id = $1 AND t.user_id = $2
RETURNING s.id, s.task_id, s.title, s.done, s.position
`

type UpdateSubtaskParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	Title    string      `json:"title"`
	Done     bool        `json:"done"`
	Position int32       `json:"position"`
}

func (q *Queries) UpdateSubtask(ctx context.Context, arg UpdateSubtaskParams) (Subtask, error) {
	row := q.db.QueryRow(ctx, updateSubtask,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Done,
		arg.Position,
	)
	var i Subtask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Done,
		&i.Position,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
  project_id = $3,
  title = $4,
  description = $5,
  priority = $6,
  status = $7,
  due_at = $8,
  estimate_minutes = $9,
  completed_at = $10,
  updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, project_id, title, description, priority, status, due_at, estimate_minutes, completed_at, created_at, updated_at
`

type UpdateTaskParams struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Priority        int16              `json:"priority"`
	Status          string             `json:"status"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
	EstimateMinutes pgtype.Int4        `json:"estimate_minutes"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.DueAt,
		arg.EstimateMinutes,
		arg.CompletedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.DueAt,
		&i.EstimateMinutes,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTimeBlock = `-- name: UpdateTimeBlock :one
UPDATE time_blocks
SET
  task_id = $3,
  title = $4,
  starts_at = $5,
  ends_at = $6
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, task_id, title, starts_at, ends_at
`

type UpdateTimeBlockParams struct {
	ID       pgtype.UUID        `json:"id"`
	UserID   pgtype.UUID        `json:"user_id"`
	TaskID   pgtype.UUID        `json:"task_id"`
	Title    string             `json:"title"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) UpdateTimeBlock(ctx context.Context, arg UpdateTimeBlockParams) (TimeBlock, error) {
	row := q.db.QueryRow(ctx, updateTimeBlock,
		arg.ID,
		arg.UserID,
		arg.TaskID,
		arg.Title,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i TimeBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}
