// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AttachTagToTask(ctx context.Context, arg AttachTagToTaskParams) error
	CheckTimeBlockOverlap(ctx context.Context, arg CheckTimeBlockOverlapParams) (int64, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (Subtask, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTimeBlock(ctx context.Context, arg CreateTimeBlockParams) (TimeBlock, error)
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	DeleteSubtask(ctx context.Context, arg DeleteSubtaskParams) error
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	DeleteTaskTagsByTaskID(ctx context.Context, taskID pgtype.UUID) error
	DeleteTimeBlock(ctx context.Context, arg DeleteTimeBlockParams) error
	DetachTagFromTask(ctx context.Context, arg DetachTagFromTaskParams) error
	GetOverdueTasks(ctx context.Context, arg GetOverdueTasksParams) ([]Task, error)
	GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error)
	GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error)
	GetTasksForRange(ctx context.Context, arg GetTasksForRangeParams) ([]GetTasksForRangeRow, error)
	GetTimeBlockByID(ctx context.Context, arg GetTimeBlockByIDParams) (TimeBlock, error)
	GetTodayTasks(ctx context.Context, arg GetTodayTasksParams) ([]Task, error)
	GetUpcomingTasks(ctx context.Context, arg GetUpcomingTasksParams) ([]Task, error)
	ListProjects(ctx context.Context, userID pgtype.UUID) ([]Project, error)
	ListSubtasksByTaskID(ctx context.Context, arg ListSubtasksByTaskIDParams) ([]Subtask, error)
	ListTags(ctx context.Context, userID pgtype.UUID) ([]Tag, error)
	ListTagsByTaskID(ctx context.Context, taskID pgtype.UUID) ([]Tag, error)
	ListTimeBlocks(ctx context.Context, arg ListTimeBlocksParams) ([]TimeBlock, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateSubtask(ctx context.Context, arg UpdateSubtaskParams) (Subtask, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTimeBlock(ctx context.Context, arg UpdateTimeBlockParams) (TimeBlock, error)
}

var _ Querier = (*Queries)(nil)
