// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessagesForUserSince = `-- name: CountMessagesForUserSince :one
SELECT COUNT(*) FROM messages m
JOIN conversations c ON m.conversation_id = c.id
WHERE c.user_id = $1
  AND m.role = 'user'
  AND m.created_at >= $2
`

type CountMessagesForUserSinceParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountMessagesForUserSince(ctx context.Context, arg CountMessagesForUserSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesForUserSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentRun = `-- name: CreateAgentRun :one
INSERT INTO agent_runs (
  conversation_id, user_id, trigger, status, iterations, input_tokens, output_tokens, error
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, conversation_id, user_id, trigger, status, iterations, input_tokens, output_tokens, error, created_at
`

type CreateAgentRunParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Trigger        string      `json:"trigger"`
	Status         string      `json:"status"`
	Iterations     int32       `json:"iterations"`
	InputTokens    int32       `json:"input_tokens"`
	OutputTokens   int32       `json:"output_tokens"`
	Error          pgtype.Text `json:"error"`
}

// Agent Runs
func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, createAgentRun,
		arg.ConversationID,
		arg.UserID,
		arg.Trigger,
		arg.Status,
		arg.Iterations,
		arg.InputTokens,
		arg.OutputTokens,
		arg.Error,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Trigger,
		&i.Status,
		&i.Iterations,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, created_at
`

type CreateConversationParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Title  string      `json:"title"`
}

// Conversations
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.UserID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, conversation_id, role, content, created_at
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Role           string      `json:"role"`
	Content        []byte      `json:"content"`
}

// Messages
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.Role, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createProposal = `-- name: CreateProposal :one
INSERT INTO proposals (user_id, run_id, summary, actions, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, run_id, summary, actions, status, created_at, decided_at
`

type CreateProposalParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	RunID   pgtype.UUID `json:"run_id"`
	Summary string      `json:"summary"`
	Actions []byte      `json:"actions"`
	Status  string      `json:"status"`
}

// Proposals
func (q *Queries) CreateProposal(ctx context.Context, arg CreateProposalParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, createProposal,
		arg.UserID,
		arg.RunID,
		arg.Summary,
		arg.Actions,
		arg.Status,
	)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.Summary,
		&i.Actions,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const createToolCall = `-- name: CreateToolCall :one
INSERT INTO tool_calls (run_id, tool_name, input, output, is_error)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, tool_name, input, output, is_error, created_at
`

type CreateToolCallParams struct {
	RunID    pgtype.UUID `json:"run_id"`
	ToolName string      `json:"tool_name"`
	Input    []byte      `json:"input"`
	Output   []byte      `json:"output"`
	IsError  bool        `json:"is_error"`
}

// Tool Calls
func (q *Queries) CreateToolCall(ctx context.Context, arg CreateToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, createToolCall,
		arg.RunID,
		arg.ToolName,
		arg.Input,
		arg.Output,
		arg.IsError,
	)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ToolName,
		&i.Input,
		&i.Output,
		&i.IsError,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = $1 AND user_id = $2
`

type DeleteConversationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) error {
	_, err := q.db.Exec(ctx, deleteConversation, arg.ID, arg.UserID)
	return err
}

const getAgentRunByID = `-- name: GetAgentRunByID :one
SELECT id, conversation_id, user_id, trigger, status, iterations, input_tokens, output_tokens, error, created_at FROM agent_runs
WHERE id = $1 AND user_id = $2
`

type GetAgentRunByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetAgentRunByID(ctx context.Context, arg GetAgentRunByIDParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getAgentRunByID, arg.ID, arg.UserID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Trigger,
		&i.Status,
		&i.Iterations,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, user_id, title, created_at FROM conversations
WHERE id = $1 AND user_id = $2
`

type GetConversationByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetConversationByID(ctx context.Context, arg GetConversationByIDParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getProposalByID = `-- name: GetProposalByID :one
SELECT id, user_id, run_id, summary, actions, status, created_at, decided_at FROM proposals
WHERE id = $1 AND user_id = $2
`

type GetProposalByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetProposalByID(ctx context.Context, arg GetProposalByIDParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, getProposalByID, arg.ID, arg.UserID)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.Summary,
		&i.Actions,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const hasBriefingForDate = `-- name: HasBriefingForDate :one
SELECT EXISTS (
  SELECT 1 FROM briefing_log
  WHERE user_id = $1 AND briefing_date = $2
)
`

type HasBriefingForDateParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	BriefingDate pgtype.Date `json:"briefing_date"`
}

func (q *Queries) HasBriefingForDate(ctx context.Context, arg HasBriefingForDateParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasBriefingForDate, arg.UserID, arg.BriefingDate)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversationsByUserID = `-- name: ListConversationsByUserID :many
SELECT id, user_id, title, created_at FROM conversations
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListConversationsByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListConversationsByUserID(ctx context.Context, arg ListConversationsByUserIDParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByConversationID = `-- name: ListMessagesByConversationID :many
SELECT id, conversation_id, role, content, created_at FROM messages
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesByConversationID(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversationID, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProposalsByUserID = `-- name: ListProposalsByUserID :many
SELECT id, user_id, run_id, summary, actions, status, created_at, decided_at FROM proposals
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProposalsByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListProposalsByUserID(ctx context.Context, arg ListProposalsByUserIDParams) ([]Proposal, error) {
	rows, err := q.db.Query(ctx, listProposalsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proposal
	for rows.Next() {
		var i Proposal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RunID,
			&i.Summary,
			&i.Actions,
			&i.Status,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCallsByRunID = `-- name: ListToolCallsByRunID :many
SELECT id, run_id, tool_name, input, output, is_error, created_at FROM tool_calls
WHERE run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListToolCallsByRunID(ctx context.Context, runID pgtype.UUID) ([]ToolCall, error) {
	rows, err := q.db.Query(ctx, listToolCallsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolCall
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ToolName,
			&i.Input,
			&i.Output,
			&i.IsError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordBriefing = `-- name: RecordBriefing :exec
INSERT INTO briefing_log (user_id, briefing_date)
VALUES ($1, $2)
ON CONFLICT (user_id, briefing_date) DO NOTHING
`

type RecordBriefingParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	BriefingDate pgtype.Date `json:"briefing_date"`
}

// Briefing Log
func (q *Queries) RecordBriefing(ctx context.Context, arg RecordBriefingParams) error {
	_, err := q.db.Exec(ctx, recordBriefing, arg.UserID, arg.BriefingDate)
	return err
}

const updateAgentRunStatus = `-- name: UpdateAgentRunStatus :one
UPDATE agent_runs
SET status = $2,
    iterations = $3,
    input_tokens = $4,
    output_tokens = $5,
    error = $6
WHERE id = $1
RETURNING id, conversation_id, user_id, trigger, status, iterations, input_tokens, output_tokens, error, created_at
`

type UpdateAgentRunStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	Iterations   int32       `json:"iterations"`
	InputTokens  int32       `json:"input_tokens"`
	OutputTokens int32       `json:"output_tokens"`
	Error        pgtype.Text `json:"error"`
}

func (q *Queries) UpdateAgentRunStatus(ctx context.Context, arg UpdateAgentRunStatusParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, updateAgentRunStatus,
		arg.ID,
		arg.Status,
		arg.Iterations,
		arg.InputTokens,
		arg.OutputTokens,
		arg.Error,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Trigger,
		&i.Status,
		&i.Iterations,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const updateProposalStatus = `-- name: UpdateProposalStatus :one
UPDATE proposals
SET status = $2,
    actions = COALESCE($3, actions),
    decided_at = $4
WHERE id = $1 AND user_id = $5
RETURNING id, user_id, run_id, summary, actions, status, created_at, decided_at
`

type UpdateProposalStatusParams struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	Actions   []byte             `json:"actions"`
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
	UserID    pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpdateProposalStatus(ctx context.Context, arg UpdateProposalStatusParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, updateProposalStatus,
		arg.ID,
		arg.Status,
		arg.Actions,
		arg.DecidedAt,
		arg.UserID,
	)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RunID,
		&i.Summary,
		&i.Actions,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}
