// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentRun struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Trigger        string             `json:"trigger"`
	Status         string             `json:"status"`
	Iterations     int32              `json:"iterations"`
	InputTokens    int32              `json:"input_tokens"`
	OutputTokens   int32              `json:"output_tokens"`
	Error          pgtype.Text        `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type BriefingLog struct {
	UserID       pgtype.UUID        `json:"user_id"`
	BriefingDate pgtype.Date        `json:"briefing_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Role           string             `json:"role"`
	Content        []byte             `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Proposal struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	RunID     pgtype.UUID        `json:"run_id"`
	Summary   string             `json:"summary"`
	Actions   []byte             `json:"actions"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
}

type ToolCall struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	ToolName  string             `json:"tool_name"`
	Input     []byte             `json:"input"`
	Output    []byte             `json:"output"`
	IsError   bool               `json:"is_error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
