// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountMessagesForUserSince(ctx context.Context, arg CountMessagesForUserSinceParams) (int64, error)
	// Agent Runs
	CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error)
	// Conversations
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	// Messages
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// Proposals
	CreateProposal(ctx context.Context, arg CreateProposalParams) (Proposal, error)
	// Tool Calls
	CreateToolCall(ctx context.Context, arg CreateToolCallParams) (ToolCall, error)
	DeleteConversation(ctx context.Context, arg DeleteConversationParams) error
	GetAgentRunByID(ctx context.Context, arg GetAgentRunByIDParams) (AgentRun, error)
	GetConversationByID(ctx context.Context, arg GetConversationByIDParams) (Conversation, error)
	GetProposalByID(ctx context.Context, arg GetProposalByIDParams) (Proposal, error)
	HasBriefingForDate(ctx context.Context, arg HasBriefingForDateParams) (bool, error)
	ListConversationsByUserID(ctx context.Context, arg ListConversationsByUserIDParams) ([]Conversation, error)
	ListMessagesByConversationID(ctx context.Context, conversationID pgtype.UUID) ([]Message, error)
	ListProposalsByUserID(ctx context.Context, arg ListProposalsByUserIDParams) ([]Proposal, error)
	ListToolCallsByRunID(ctx context.Context, runID pgtype.UUID) ([]ToolCall, error)
	// Briefing Log
	RecordBriefing(ctx context.Context, arg RecordBriefingParams) error
	UpdateAgentRunStatus(ctx context.Context, arg UpdateAgentRunStatusParams) (AgentRun, error)
	UpdateProposalStatus(ctx context.Context, arg UpdateProposalStatusParams) (Proposal, error)
}

var _ Querier = (*Queries)(nil)
