// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Kind      string             `json:"kind"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Read      bool               `json:"read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reminder struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	Message   string             `json:"message"`
	RemindAt  pgtype.Timestamptz `json:"remind_at"`
	Fired     bool               `json:"fired"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
