// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotifications = `-- name: CountNotifications :one
SELECT count(*) FROM notifications
WHERE user_id = $1
`

func (q *Queries) CountNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
  user_id,
  kind,
  title,
  body
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, kind, title, body, read, created_at
`

type CreateNotificationParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Kind   string      `json:"kind"`
	Title  string      `json:"title"`
	Body   string      `json:"body"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.Body,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (
  user_id,
  task_id,
  message,
  remind_at
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, task_id, message, remind_at, fired, created_at
`

type CreateReminderParams struct {
	UserID   pgtype.UUID        `json:"user_id"`
	TaskID   pgtype.UUID        `json:"task_id"`
	Message  string             `json:"message"`
	RemindAt pgtype.Timestamptz `json:"remind_at"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder,
		arg.UserID,
		arg.TaskID,
		arg.Message,
		arg.RemindAt,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Message,
		&i.RemindAt,
		&i.Fired,
		&i.CreatedAt,
	)
	return i, err
}

const getDueRemindersForUpdate = `-- name: GetDueRemindersForUpdate :many
SELECT id, user_id, task_id, message, remind_at
FROM reminders
WHERE remind_at <= $1 AND fired = false
ORDER BY remind_at ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type GetDueRemindersForUpdateParams struct {
	RemindAt pgtype.Timestamptz `json:"remind_at"`
	Limit    int32              `json:"limit"`
}

type GetDueRemindersForUpdateRow struct {
	ID       pgtype.UUID        `json:"id"`
	UserID   pgtype.UUID        `json:"user_id"`
	TaskID   pgtype.UUID        `json:"task_id"`
	Message  string             `json:"message"`
	RemindAt pgtype.Timestamptz `json:"remind_at"`
}

func (q *Queries) GetDueRemindersForUpdate(ctx context.Context, arg GetDueRemindersForUpdateParams) ([]GetDueRemindersForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getDueRemindersForUpdate, arg.RemindAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueRemindersForUpdateRow
	for rows.Next() {
		var i GetDueRemindersForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Message,
			&i.RemindAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT count(*) FROM notifications
WHERE user_id = $1 AND read = false
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, kind, title, body, read, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemindersByUserID = `-- name: ListRemindersByUserID :many
SELECT id, user_id, task_id, message, remind_at, fired, created_at FROM reminders
WHERE user_id = $1
ORDER BY remind_at ASC
`

func (q *Queries) ListRemindersByUserID(ctx context.Context, userID pgtype.UUID) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listRemindersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Message,
			&i.RemindAt,
			&i.Fired,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET read = true
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, kind, title, body, read, created_at
`

type MarkNotificationAsReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const markReminderFired = `-- name: MarkReminderFired :exec
UPDATE reminders
SET fired = true
WHERE id = $1
`

func (q *Queries) MarkReminderFired(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markReminderFired, id)
	return err
}
