// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountNotifications(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error)
	GetDueRemindersForUpdate(ctx context.Context, arg GetDueRemindersForUpdateParams) ([]GetDueRemindersForUpdateRow, error)
	GetUnreadNotificationCount(ctx context.Context, userID pgtype.UUID) (int64, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListRemindersByUserID(ctx context.Context, userID pgtype.UUID) ([]Reminder, error)
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error)
	MarkReminderFired(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
